### ISSUE TITLE
[Feature] Remove "Craft" interaction 

### ISSUE THREAD

**Issue by MbtMarco** [TheHangel/the-fletching-table-mod#2]
It would be more coherent to have crafting similar to anvil, where to confirm the craft it would be enough to select the final result.

**Comment by TheHangel** [comment]
You are using an old version.
The craft interaction has been removed since the 1.19.4 MC version.

**Comment by TheHangel** [comment]
@MbtMarco 
Since 1.4, the Minecraft 1.16.5 Forge version of the mod has no "Craft button" anymore.
